web:
  build: .
  ports:
    - "127.0.0.1:4005:4005"
    - "9999:80"
  links:
    - pg
  stdin_open: true
pg:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=nuit
    - POSTGRES_PASSWORD=nuit
